#!/bin/bash
#########################
# COMPILAR
#########################
if [ -f *.java ]; then
    for file in ./*.java
    do
	javac $file
	base=$(basename $file .java)
	echo "#!/bin/bash" > a.out
	echo "cat - | java $base" >> a.out
	break;
    done
    chmod 755 a.out
elif [ -f *.py ]; then
    for file in *.py
    do
	cp $file a.out
	break;
    done
    chmod 755 a.out
elif [ -f *.c ]; then
    for file in *.c
    do
	gcc $file
	break;
    done
elif [ -f *.cpp ]; then 
    for file in *.cpp
    do
	g++ $file
	break;
    done
else
    PWD=$(pwd)
    echo "Nenhum arquivo contendo o código fonte foi encontrado no diretório $PWD"
    exit
fi

#########################
# EXECUTAR TESTES
#########################
    COUNTER=0
    GRADE=0
    rm -rf ./test 2> /dev/null
    mkdir test
    while [ -f ./in/file$COUNTER ]; do
        touch ./test/file$COUNTER
	./a.out < ./in/file$COUNTER > ./test/file$COUNTER	
        DIFF=$(diff -w ./test/file$COUNTER ./out/file$COUNTER) 
        if [ "$DIFF" == "" ]; then
            let GRADE=GRADE+1
	    echo "$COUNTER ok"
        else 
            echo "Erro no $COUNTER"
        fi
	let COUNTER=COUNTER+1
    done
    #rm -rf ./test
    echo "Nota: $GRADE de $COUNTER"
